# Generated by Django 4.2.1 on 2023-05-12 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_management_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='full_name',
            new_name='first_name',
        ),
    ]
